#!/bin/sh
set -eu

PREFIX=${PREFIX:-/usr/local}
CONFIG_DIR=${CONFIG_DIR:-/etc/fs-tracker}
SERVICE_DIR=${SERVICE_DIR:-/etc/systemd/system}
REGISTRY_FILE=${REGISTRY_FILE:-$CONFIG_DIR/canaries}
CANARY_NAME=${CANARY_NAME:-default}
TARGET_PATH=/srv/honey/credentials.txt
LOG_PATH=/var/log/fs-tracker/events.jsonl
ACTION_PATH=

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
. "$SCRIPT_DIR/canary-registry.sh"

require_root
require_no_arguments "$@"
require_interactive

printf 'fs-tracker interactive setup\n\n'
prompt_new_canary_name

SERVICE_NAME="fs-file-monitor-$CANARY_NAME.service"
CONFIG_FILE="$CONFIG_DIR/$CANARY_NAME.conf"
SERVICE_FILE="$SERVICE_DIR/$SERVICE_NAME"

[ ! -e "$SERVICE_FILE" ] || fail "$SERVICE_FILE already exists; choose another canary name or deactivate it first"
[ ! -e "$CONFIG_FILE" ] || fail "$CONFIG_FILE already exists; choose another canary name or deactivate it first"
[ ! -e "$REGISTRY_FILE" ] || ! registry_contains "$CANARY_NAME" || fail "canary '$CANARY_NAME' is already registered; choose another name"

printf 'Service: %s\n' "$SERVICE_NAME"
printf 'Target file [%s]: ' "$TARGET_PATH"
IFS= read -r input
[ -n "$input" ] && TARGET_PATH=$input

printf 'JSONL log file [%s]: ' "$LOG_PATH"
IFS= read -r input
[ -n "$input" ] && LOG_PATH=$input

printf 'Executable action file [none]: '
IFS= read -r input
[ -n "$input" ] && ACTION_PATH=$input

MAIL_TO=
MAIL_FROM=
MAIL_SUBJECT=
if [ -n "$ACTION_PATH" ]; then
    ACTION_NAME=$(basename -- "$ACTION_PATH")
    if [ "$ACTION_NAME" = "canary-mail-send.sh" ] || [ "$ACTION_NAME" = "canary-mail-send" ]; then
        printf 'Mail recipient (required): '
        IFS= read -r input
        MAIL_TO=$input
        if [ -z "$MAIL_TO" ]; then
            fail "mail action requires a recipient address"
        fi

        HOSTNAME_SHORT=$(hostname 2>/dev/null || printf 'localhost')
        printf 'Mail sender [%s]: ' "fs-tracker@$HOSTNAME_SHORT"
        IFS= read -r input
        [ -n "$input" ] && MAIL_FROM=$input
        MAIL_FROM=${MAIL_FROM:-"fs-tracker@$HOSTNAME_SHORT"}

        printf 'Mail subject [fs-tracker alert]: '
        IFS= read -r input
        [ -n "$input" ] && MAIL_SUBJECT=$input
        MAIL_SUBJECT=${MAIL_SUBJECT:-fs-tracker alert}
    fi
fi

case "$TARGET_PATH:$LOG_PATH:$ACTION_PATH" in
    /*:/*:) ;;
    /*:/*:/*) [ -x "$ACTION_PATH" ] || fail "action file must be executable" ;;
    *) fail "target and log paths must be absolute; action must be an executable absolute path" ;;
esac

[ ! -e "$TARGET_PATH" ] || [ ! -d "$TARGET_PATH" ] || fail "target path must be a file"

printf '\nTarget: %s\n' "$TARGET_PATH"
printf 'Log:    %s\n' "$LOG_PATH"
printf 'Install and start the systemd service? [y/N] '
IFS= read -r answer
case "$answer" in
    y|Y|yes|YES) ;;
    *) printf 'Installation cancelled.\n'; exit 0 ;;
esac

PROJECT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
BINARY="$PROJECT_DIR/dist/fs-tracker"

printf 'Building fs-tracker...\n'
make -C "$PROJECT_DIR" test
make -C "$PROJECT_DIR"
[ -x "$BINARY" ] || fail "build did not produce $BINARY"

install -d -m 0755 "$PREFIX/bin"
install -m 0755 "$BINARY" "$PREFIX/bin/fs-tracker"

TARGET_DIR=$(dirname -- "$TARGET_PATH")
LOG_DIR=$(dirname -- "$LOG_PATH")
install -d -m 0750 "$CONFIG_DIR"
install -d -m 0750 "$TARGET_DIR"
install -d -m 0750 "$LOG_DIR"

if [ ! -e "$TARGET_PATH" ]; then
    install -m 0640 /dev/null "$TARGET_PATH"
fi

cat > "$CONFIG_FILE" <<EOF
# Generated by install-fs-tracker.sh.
TRACK_PATH=$TARGET_PATH
TRACK_LOG=$LOG_PATH
EOF
if [ -n "$ACTION_PATH" ]; then
    printf 'TRACK_ACTION=%s\n' "$ACTION_PATH" >> "$CONFIG_FILE"
fi
chmod 0644 "$CONFIG_FILE"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=File activity monitor ($CANARY_NAME)
After=local-fs.target

[Service]
Type=simple
ExecStart=$PREFIX/bin/fs-tracker --config $CONFIG_FILE
Restart=on-failure
EOF

if [ -n "$MAIL_TO" ]; then
    cat >> "$SERVICE_FILE" <<EOF
Environment="FS_TRACKER_MAIL_TO=$MAIL_TO"
Environment="MAIL_TO=$MAIL_TO"
Environment="FS_TRACKER_MAIL_FROM=$MAIL_FROM"
Environment="MAIL_FROM=$MAIL_FROM"
Environment="FS_TRACKER_MAIL_SUBJECT=$MAIL_SUBJECT"
Environment="MAIL_SUBJECT=$MAIL_SUBJECT"
EOF
fi

cat >> "$SERVICE_FILE" <<EOF

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 "$SERVICE_FILE"

systemctl daemon-reload
systemctl enable --now "$SERVICE_NAME"
registry_add

printf '\nfs-tracker is active.\n'
printf 'Service: %s\n' "$SERVICE_NAME"
printf 'Target: %s\n' "$TARGET_PATH"
printf 'Log:    %s\n' "$LOG_PATH"
printf 'Status: systemctl status %s\n' "$SERVICE_NAME"
printf 'Events: journalctl -u %s -f\n' "$SERVICE_NAME"
