#!/bin/sh
set -eu

PREFIX=${PREFIX:-/usr/local}
CONFIG_FILE=${CONFIG_FILE:-/etc/fs-tracker.conf}
SERVICE_FILE=${SERVICE_FILE:-/etc/systemd/system/fs-tracker.service}
TARGET_PATH=/srv/honey/credentials.txt
LOG_PATH=/var/log/fs-tracker/events.jsonl

fail() {
    printf 'error: %s\n' "$1" >&2
    exit 1
}

case "$(id -u)" in
    0) ;;
    *) fail "run this script as root, for example: sudo $0" ;;
esac

[ "$#" -eq 0 ] || fail "this installer is interactive; do not pass arguments"
[ -t 0 ] || fail "interactive terminal input is required"

printf 'fs-tracker interactive setup\n\n'
printf 'Target file [%s]: ' "$TARGET_PATH"
IFS= read -r input
[ -n "$input" ] && TARGET_PATH=$input

printf 'JSONL log file [%s]: ' "$LOG_PATH"
IFS= read -r input
[ -n "$input" ] && LOG_PATH=$input

case "$TARGET_PATH:$LOG_PATH" in
    /*:/*) ;;
    *) fail "target and log paths must be absolute" ;;
esac

[ ! -e "$TARGET_PATH" ] || [ ! -d "$TARGET_PATH" ] || fail "target path must be a file"

printf '\nTarget: %s\n' "$TARGET_PATH"
printf 'Log:    %s\n' "$LOG_PATH"
printf 'Install and start the systemd service? [y/N] '
IFS= read -r answer
case "$answer" in
    y|Y|yes|YES) ;;
    *) printf 'Installation cancelled.\n'; exit 0 ;;
esac

SCRIPT_DIR=$(CDPATH= cd -- "$(dirname -- "$0")" && pwd)
PROJECT_DIR=$(CDPATH= cd -- "$SCRIPT_DIR/.." && pwd)
BINARY="$PROJECT_DIR/dist/fs-tracker"

printf 'Building fs-tracker...\n'
make -C "$PROJECT_DIR" test
make -C "$PROJECT_DIR"
[ -x "$BINARY" ] || fail "build did not produce $BINARY"

install -d -m 0755 "$PREFIX/bin"
install -m 0755 "$BINARY" "$PREFIX/bin/fs-tracker"

TARGET_DIR=$(dirname -- "$TARGET_PATH")
LOG_DIR=$(dirname -- "$LOG_PATH")
install -d -m 0750 "$TARGET_DIR"
install -d -m 0750 "$LOG_DIR"

if [ ! -e "$TARGET_PATH" ]; then
    install -m 0640 /dev/null "$TARGET_PATH"
fi

cat > "$CONFIG_FILE" <<EOF
# Generated by install-fs-tracker.sh.
TRACK_PATH=$TARGET_PATH
TRACK_LOG=$LOG_PATH
EOF
chmod 0644 "$CONFIG_FILE"

cat > "$SERVICE_FILE" <<EOF
[Unit]
Description=Minimal fanotify file activity tracker
After=local-fs.target

[Service]
Type=simple
ExecStart=$PREFIX/bin/fs-tracker --config $CONFIG_FILE
Restart=on-failure

[Install]
WantedBy=multi-user.target
EOF
chmod 0644 "$SERVICE_FILE"

systemctl daemon-reload
systemctl enable --now fs-tracker.service

printf '\nfs-tracker is active.\n'
printf 'Target: %s\n' "$TARGET_PATH"
printf 'Log:    %s\n' "$LOG_PATH"
printf 'Status: systemctl status fs-tracker.service\n'
printf 'Events: journalctl -u fs-tracker.service -f\n'
